Repository ChristophWurst/nextcloud_sentry, pull requests merged in 2023-12, with the labels that each got.

#641 feat(deps): Add Nextcloud 29 support
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
  appinfo/info.xml
Labels: enhancement, 3. to review

#642 feat(deps): Add PHP8.3 support
  .github/workflows/lint.yml
  .github/workflows/test.yml
  appinfo/info.xml
Labels: enhancement, dependencies, 3. to review

#634 fix(config): cast config returned by getSystemValue to float as the function return type expects
  lib/Config.php
Labels: bug, 3. to review, php
